class Rule:
    id = "309"
    description = "Verify Route Map name lengths"
    severity = "HIGH"

    @classmethod
    def _extract_route_controls(cls, bgp_peers, tenant_name, l3out_name, l3out_config):
        """Helper function to reduce code duplication."""
        for bgp_peer in bgp_peers:
            peer_address = bgp_peer.get("ip")
            for direction in ["import_route_control", "export_route_control"]:
                profile = bgp_peer.get(direction)
                if profile:
                    l3out_config.append(
                        (tenant_name, l3out_name, peer_address, profile)
                    )

    @classmethod
    def _extract_contexts(cls, route_map_name, contexts, route_map_data):
        """Helper function to reduce code duplication."""
        for context in contexts:
            context_name = context.get("name", "")
            for match_rule in context.get("match_rules", []):
                route_map_data.append((route_map_name, context_name, match_rule))

    @classmethod
    def _validate_route_control_name_length(cls, inventory):
        """Verify length of Route Map For Route Control."""
        results = []
        l3out_config = []
        # Use a dictionary for route maps for efficient O(1) lookups
        policies_route_maps = {}

        tenants = inventory.get("apic", {}).get("tenants", [])

        # --- 1. Collect all data in a single pass over tenants ---
        for tenant in tenants:
            tenant_name = tenant["name"]

            # Collect L3Out route control profiles
            for l3out in tenant.get("l3outs", []):
                l3out_name = l3out["name"]

                # START: ADDED LOGIC FOR MISSING SCENARIO
                # Scenario 4: Autogenerated Node Profiles (bgp_peers directly under l3out)
                cls._extract_route_controls(
                    l3out.get("bgp_peers", []),
                    tenant_name,
                    l3out_name,
                    l3out_config,
                )
                # END: ADDED LOGIC

                # Scenario 1 & 2: Explicit Profiles
                for node_profile in l3out.get("node_profiles", []):
                    cls._extract_route_controls(
                        node_profile.get("bgp_peers", []),
                        tenant_name,
                        l3out_name,
                        l3out_config,
                    )
                    for if_profile in node_profile.get("interface_profiles", []):
                        for interface in if_profile.get("interfaces", []):
                            cls._extract_route_controls(
                                interface.get("bgp_peers", []),
                                tenant_name,
                                l3out_name,
                                l3out_config,
                            )

                # Scenario 3: Autogenerated Interface Profiles
                for node in l3out.get("nodes", []):
                    for interface in node.get("interfaces", []):
                        cls._extract_route_controls(
                            interface.get("bgp_peers", []),
                            tenant_name,
                            l3out_name,
                            l3out_config,
                        )

            # Collect route map policies and store in a dictionary
            policies = tenant.get("policies", {})
            for route_map in policies.get("route_control_route_maps", []):
                route_map_name = route_map.get("name")
                if not route_map_name:
                    continue

                if route_map_name not in policies_route_maps:
                    policies_route_maps[route_map_name] = []

                for context in route_map.get("contexts", []):
                    context_name = context.get("name", "")
                    for match_rule in context.get("match_rules", []):
                        policies_route_maps[route_map_name].append(
                            (context_name, match_rule)
                        )

        # --- 2. Perform validation using efficient lookups ---
        LIMIT = 135
        for tenant, l3out_name, peer_address, profile_name in l3out_config:
            if profile_name in policies_route_maps:
                for context_name, match_rule in policies_route_maps[profile_name]:
                    total_len = (
                        len(tenant)
                        + len(l3out_name)
                        + len(peer_address)
                        + len(profile_name)
                        + len(context_name)
                        + len(match_rule)
                    )
                    if total_len > LIMIT:
                        results.append(
                            f"The sum of lengths for Tenant ({tenant}), "
                            f"L3Out ({l3out_name}), Profile ({profile_name}), "
                            f"Context ({context_name}), Peer Address ({peer_address}), "
                            f"and MatchRule ({match_rule}) exceeded the limit of {LIMIT} "
                            f"by {total_len - LIMIT} characters."
                        )

        return results

    @classmethod
    def _validate_l3out_route_map_context_name_length(cls, inventory):
        """Verify length of L3Out Route Map Profile, Context and Match Rule names."""
        results = []

        tenants = inventory.get("apic", {}).get("tenants", [])

        LIMIT = 93
        for tenant in tenants:
            tenant_name = tenant["name"]

            for l3out in tenant.get("l3outs", []):
                l3out_name = l3out["name"]
                route_map_data = []

                # Scenario 1: route_maps (user-defined name)
                for route_map in l3out.get("route_maps", []):
                    route_map_name = route_map.get("name", "")
                    if not route_map_name:
                        continue
                    cls._extract_contexts(
                        route_map_name,
                        route_map.get("contexts", []),
                        route_map_data,
                    )

                # Scenario 2: import_route_map (default name: "default-import")
                import_rm = l3out.get("import_route_map")
                if import_rm:
                    import_rm_name = import_rm.get("name", "default-import")
                    cls._extract_contexts(
                        import_rm_name,
                        import_rm.get("contexts", []),
                        route_map_data,
                    )

                # Scenario 3: export_route_map (default name: "default-export")
                export_rm = l3out.get("export_route_map")
                if export_rm:
                    export_rm_name = export_rm.get("name", "default-export")
                    cls._extract_contexts(
                        export_rm_name,
                        export_rm.get("contexts", []),
                        route_map_data,
                    )

                # Validation
                for route_map_name, context_name, match_rule in route_map_data:
                    total_len = (
                        len(route_map_name) + len(context_name) + len(match_rule)
                    )
                    if total_len > LIMIT:
                        results.append(
                            f"The sum of lengths for Tenant ({tenant_name}), "
                            f"L3Out ({l3out_name}), Profile ({route_map_name}), "
                            f"Context ({context_name}), and MatchRule ({match_rule}) "
                            f"exceeded the limit of {LIMIT} "
                            f"by {total_len - LIMIT} characters."
                        )

        return results

    @classmethod
    def match(cls, inventory):
        results = []
        try:
            results.extend(cls._validate_route_control_name_length(inventory))
        except KeyError:
            pass
        except Exception as e:
            results.append(
                f"Rule {cls.id} (route_control) - An unexpected error occurred: {e}"
            )
        try:
            results.extend(cls._validate_l3out_route_map_context_name_length(inventory))
        except KeyError:
            pass
        except Exception as e:
            results.append(
                f"Rule {cls.id} (l3out_context) - An unexpected error occurred: {e}"
            )
        return results
